FROM python:3.8
LABEL maintainer="mcolli11@uoregon.edu"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY . /app
RUN chmod 755 run_tests.sh
RUN ./run_tests.sh